# Generated by Django 4.0.4 on 2022-06-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bridges', '0001_initial'),
        ('girder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fcuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=64, verbose_name='사용자 아이디')),
                ('username', models.CharField(max_length=64, verbose_name='사용자명')),
                ('useremail', models.EmailField(max_length=128, verbose_name='사용자이메일')),
                ('ptags', models.ManyToManyField(to='bridges.bridges', verbose_name='교량')),
                ('tags', models.ManyToManyField(to='girder.girder', verbose_name='거더')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'user',
            },
        ),
    ]
