# Generated by Django 4.0.4 on 2022-06-27 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcuser',
            old_name='ptags',
            new_name='brdiges',
        ),
        migrations.RenameField(
            model_name='fcuser',
            old_name='tags',
            new_name='girder',
        ),
    ]
