# Generated by Django 4.0.4 on 2022-08-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridges',
            name='length',
            field=models.CharField(default='', max_length=32, verbose_name='교량 길이'),
        ),
        migrations.AddField(
            model_name='bridges',
            name='section',
            field=models.CharField(default='', max_length=32, verbose_name='section'),
        ),
        migrations.AddField(
            model_name='bridges',
            name='writer',
            field=models.CharField(default='', max_length=32, verbose_name='등록자'),
        ),
    ]
